Made it where all resources (volume, svm, filesystem) have all actions (list, create, delete); Also renamed the directory to be more descriptive.

diff --git a/FSx_ONTAP_AWS_CLI_Scripts/create_fsxn_volume b/FSx_ONTAP_AWS_CLI_Scripts/create_fsxn_volume
--- a/FSx_ONTAP_AWS_CLI_Scripts/create_fsxn_volume
+++ b/FSx_ONTAP_AWS_CLI_Scripts/create_fsxn_volume
@@ -17,11 +17,11 @@
 ################################################################################
 
 ################################################################################
-#  This function just outputs the usage information and exits.
+# This function just outputs the usage information and exits.
 ################################################################################
 usage () {
 cat 1>&2 <<EOF
-Usage: $(basename $0) -m svmId -n volumeName [-r region] [-s size]
+Usage: $(basename $0) -i svmID -n volumeName [-r region] [-s size]
 where
   svmID: is the SVM ID in the filesystem you want to create the volume.
   volumeName: is the name you want to assign the volume.
@@ -34,15 +34,17 @@ EOF
 ################################################################################
 # Main logic starts here.
 ################################################################################
+tmpout=/tmp/create_volume.$$
+trap 'rm -f $tmpout' exit
 #
 # Set some defaults.
 size=20
 region=$(aws configure list | egrep '^.*egion ' | awk '{print $2}')
 #
 # Process command line arguments.
-while getopts "m:n:r:s:" option; do
+while getopts "i:n:r:s:" option; do
   case $option in
-    m) svmId=$OPTARG
+    i) svmId=$OPTARG
       ;;
     n) volumeName=$OPTARG
       ;;
@@ -59,7 +61,6 @@ done
 if [ -z "$volumeName" -o -z "$svmId" ]; then
   echo "Error, you must provide a volume name and SVM ID." 1>&2
   usage
-  exit 1
 fi
 
 aws fsx create-volume --volume-type ONTAP --name $volumeName --ontap-configuration "{
@@ -70,4 +71,20 @@ aws fsx create-volume --volume-type ONTAP --name $volumeName --ontap-configurati
   \"StorageVirtualMachineId\": \"$svmId\",
   \"TieringPolicy\" : {\"CoolingPeriod\": 31, \"Name\": \"SNAPSHOT_ONLY\"},
   \"OntapVolumeType\": \"RW\",
-  \"SnapshotPolicy\": \"default\"}" --region=$region
+  \"SnapshotPolicy\": \"default\"}" --region=$region --output=json > $tmpout 2>&1
+
+if [ $? != "0" ]; then
+  echo "Failed to create the FSxN volume." 1>&2
+  cat $tmpout 1>&2
+  exit 1
+else
+  status=$(jq -r .Volume.Lifecycle $tmpout 2> /dev/null)
+  if [ "$status" == "CREATING" -o "$status" == "PENDING" ]; then
+    echo "FSxN volume '$volumeName'($(jq -r .Volume.VolumeId $tmpout)) is being created."
+    exit 0
+  else
+    echo "Unknown status '$status'. Complete output returned from the AWS api:" 1>&2
+    cat $tmpout 1>&2
+    exit 1
+  fi
+fi
diff --git a/FSx_ONTAP_AWS_CLI_Scripts/delete_fsxn_svm b/FSx_ONTAP_AWS_CLI_Scripts/delete_fsxn_svm
--- a/FSx_ONTAP_AWS_CLI_Scripts/delete_fsxn_svm
+++ b/FSx_ONTAP_AWS_CLI_Scripts/delete_fsxn_svm
@@ -12,8 +12,8 @@
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ################################################################################
 #
-# This script is used to delete an FSxN volume.
-#
+# This script is used to delete a storage virtual machine from a
+# FSxN filesystem.
 ################################################################################
 
 ################################################################################
@@ -21,10 +21,10 @@
 ################################################################################
 usage () {
 cat 1>&2 <<EOF
-Usage: $(basename $0) -v volumeId [-r region]
-where
-  volumeId: is the ID of the volume to delete.
-  region: is the AWS region where the FSxN filesystem resides.
+Usage: $(basename $0) -i svmID [-r region] 
+Where:
+  svmID: Is the ID of the storage virtual machine you want to delete.
+  region: Is the AWS region where the SVM resides.
 EOF
   exit 1
 }
@@ -32,26 +32,55 @@ EOF
 ################################################################################
 # Main logic starts here.
 ################################################################################
+tmpout=/tmp/fsx_svm_create.$$
+volumesFile=/tmp/fsx_svm_create-volumes.$$
+trap 'rm -f $tmpout volumesFile' exit
+
+if which aws jq > /dev/null 2>&1; then
+  :
+else
+  echo "Error, both the 'aws' and 'jq' commands are required to run this script." 1>&2
+  exit 1
+fi
 #
-# Set some defaults.
+# Set any defaults.
 region=$(aws configure list | egrep '^.*egion ' | awk '{print $2}')
 #
 # Process command line arguments.
-while getopts "v:" option; do
+while getopts "i:r:" option; do
   case $option in
-    r) region="$OPTARG"
+    i) svmID=$OPTARG
       ;;
-    v) volumeId="$OPTARG"
+    r) region=$OPTARG
       ;;
-    *) usage
+    *) echo "Error, unknown option '$option'." 1>&2
+      usage
       ;;
   esac
+  shift
 done
 #
 # Ensure all the required parameters have been provided.
-if [ -z "$volumeId" ]; then
-  echo "Error, you must provide volume ID." 1>&2
+if [ -z "$svmID" ]; then
+  echo "Error, missing reuqired arguments." 1>&2
   usage
+  exit 1
 fi
 
-aws fsx delete-volume --volume-id $volumeId --region=$region
+aws fsx delete-storage-virtual-machine --region=$region --storage-virtual-machine-id $svmID > $tmpout 2>&1
+
+if [ $? != "0" ]; then
+  echo "Failed to delete storage virtual machine." 1>&2
+  cat $tmpout
+  exit 1
+else
+  status=$(jq -r .Lifecycle $tmpout)
+  if [ "$status" == "DELETING" ]; then
+    echo "Storage Virtual Machine with an id of '$svmID' is being deleted."
+    exit 0
+  else
+    echo "Unknown status '$status'. Complete output returned from the AWS api:"
+    cat $tmpout
+    exit 1
+  fi
+fi
