Renamed the file; Added a -f option to limit the output to a specific file system.

diff --git a/FSx_ONTAP_AWS_CLI_Scripts/list_fsxn_volumes b/FSx_ONTAP_AWS_CLI_Scripts/list_fsxn_volumes
--- a/FSx_ONTAP_AWS_CLI_Scripts/list_fsxn_volumes
+++ b/FSx_ONTAP_AWS_CLI_Scripts/list_fsxn_volumes
@@ -28,12 +28,14 @@
 ################################################################################
 usage () {
   cat 1>&2 <<EOF
-Usage $(basename $0) [-r region] [-a] [-n] [-f] [-s svmID]
+Usage $(basename $0) [-r region] [-a] [-o] [-f fileSystemName] [-i fileSystemId] [-n] [-s svmID]
   Where: -r region allows you to specify the region you want the list from.
          -a means all regions.
-         -f means include the file system name.
+         -n means include the file system name.
+         -f fileSystemName means to only include volumes that are under the named file system.
+         -i fileSystemId means to only include volumes that are under the file system with the specified file system ID.
          -s svmID - Only show volumes that are under the specified SVM ID.
-         -n means to exclude svm root volumes. Only works in conjunction with the -s option.
+         -o means to exclude svm root volumes. Only works in conjunction with the -s option.
 EOF
   exit 1
 }
@@ -59,15 +61,34 @@ allRegions=false
 region=$(aws configure list | egrep '^.*egion ' | awk '{print $2}')
 includeFsName=false
 excludeRoot=false
-while getopts "fanr:s:" option; do
+filter=""
+fsid=""
+fileSystemName=""
+while getopts "r:af:i:nos:" option; do
   case "$option" in
     r) region="$OPTARG"
       ;;
     a) allRegions=true
       ;;
-    f) includeFsName=true
+    f) fileSystemName="$OPTARG"
+      fsid=$(aws fsx describe-file-systems --output=json 2> /dev/null | jq -r ".FileSystems[] | if((.Tags[] | select(.Key == \"Name\") .Value) == \"${fileSystemName}\") then .FileSystemId else empty end" 2> /dev/null)
+      if [ -z "$fsid" ]; then
+        echo "Error, failed to find the file system with the file system name of '$OPTARG'." 1>&2
+        exit 1
+      fi
+      filter='--filters [{"Name":"file-system-id","Values":["'$fsid'"]}]'
       ;;
-    n) excludeRoot=true
+    i) fileSystemName=$(aws fsx describe-file-systems --output=json 2> /dev/null | jq -r ".FileSystems[] | if(.FileSystemId == \"$OPTARG\") then (.Tags[] | select(.Key == \"Name\") .Value) else empty end" 2> /dev/null)
+      if [ -z "$fileSystemName" ]; then
+        echo "Error, failed to find the file system with the file system ID of '$OPTARG'." 1>&2
+        exit 1
+      fi
+      filter='--filters [{"Name":"file-system-id","Values":["'$OPTARG'"]}]'
+      ;;
+    n) includeFsName=true
+      ;;
+    o) excludeRoot=true
+      er="and (.OntapConfiguration.StorageVirtualMachineRoot | not)"
       ;;
     s) svmID="$OPTARG"
       ;;
@@ -89,17 +110,21 @@ for region in $regions; do
   # Check that the fsx service is supported in thie region
   if [ ! -z "$(getent hosts fsx.$region.amazonaws.com)" ]; then
     if [ -z "$svmID" ]; then
-      aws fsx describe-volumes --region=$region | jq -r '.Volumes[] | .FileSystemId + "," + .Name + "," + .VolumeId' | sort > $tmpout
+      if [ "$excludeRoot" != "true" ]; then
+        aws fsx describe-volumes $filter --region=$region --output=json | jq -r '.Volumes[] | .FileSystemId + "," + .Name + "," + .VolumeId' | sort > $tmpout
+      else
+        aws fsx describe-volumes $filter --region=$region --output=json | jq -r '.Volumes[] | if(.OntapConfiguration.StorageVirtualMachineRoot | not) then .FileSystemId + "," + .Name + "," + .VolumeId else empty end' | sort > $tmpout
+      fi
     else
       if [ "$excludeRoot" != "true" ]; then
-        aws fsx describe-volumes --region=$region | jq -r ".Volumes[] | if(.OntapConfiguration.StorageVirtualMachineId == \"$svmID\") then .FileSystemId + \",\" + .Name + \",\" + .VolumeId else empty end" | sort > $tmpout
+        aws fsx describe-volumes $filter --region=$region --output=json | jq -r ".Volumes[] | if(.OntapConfiguration.StorageVirtualMachineId == \"$svmID\") then .FileSystemId + \",\" + .Name + \",\" + .VolumeId else empty end" | sort > $tmpout
       else
-        aws fsx describe-volumes --region=$region | jq -r ".Volumes[] | if(.OntapConfiguration.StorageVirtualMachineId == \"$svmID\" and (.OntapConfiguration.StorageVirtualMachineRoot | not)) then .FileSystemId + \",\" + .Name + \",\" + .VolumeId else empty end" | sort > $tmpout
+        aws fsx describe-volumes $filter --region=$region --output=json | jq -r ".Volumes[] | if(.OntapConfiguration.StorageVirtualMachineId == \"$svmID\" and (.OntapConfiguration.StorageVirtualMachineRoot | not)) then .FileSystemId + \",\" + .Name + \",\" + .VolumeId else empty end" | sort > $tmpout
       fi
     fi
   
     if [ $includeFsName == "true" ]; then
-      aws fsx describe-file-systems --region=$region | jq -r '.FileSystems[] | .FileSystemId + "," + (.Tags[] | select(.Key == "Name") .Value)' > $tmpout2
+      aws fsx describe-file-systems --region=$region --output=json | jq -r '.FileSystems[] | .FileSystemId + "," + (.Tags[] | select(.Key == "Name") .Value)' | fgrep "$fileSystemName" > $tmpout2
       awk -F, -v region=$region 'BEGIN {first=1; maxNameLen=0; while(getline < "'$tmpout2'") {fss[$1]=$2; if(length($2) > maxNameLen) {maxNameLen=length($2)}}; maxNameLen +=2; formatStr="%12s %20s%-"maxNameLen"s %23s %s\n"}; {if(first) {printf "\n"; printf formatStr, "Region", "FileSystem ID", "(Name)", "Volume ID", "Volume Name"; first=0}; name="("fss[$1]")"; printf formatStr, region, $1, name, $3, $2}' < $tmpout
     else
       awk -F, -v region=$region 'BEGIN {first=1; formatStr="%12s %23s %23s %s\n"}; {if(first) {printf "\n"; printf formatStr, "Region", "FileSystem ID", "Volume ID", "Volume Name"; first=0}; printf formatStr, region, $1, $3, $2}' < $tmpout
