Added new scripts.

diff --git a/Management-Utilities/Workload-Factory-API-Samples/fsxn_credentials_set b/Management-Utilities/Workload-Factory-API-Samples/fsxn_credentials_set
--- a/Management-Utilities/Workload-Factory-API-Samples/fsxn_credentials_set
+++ b/Management-Utilities/Workload-Factory-API-Samples/fsxn_credentials_set
@@ -104,14 +104,14 @@ required_options["FILESYSTEM_ID"]='Error: The ID of the FSxN file system is requ
 
 check_required_options
 
-if [ -n "$USER_ID" -a -n "$SECRET_ARN" ]; then
+if [ \( -n "$USER_ID" -o -n "$PASSWORD" \) -a -n "$SECRET_ARN" ]; then
   echo "Error: You can only provide either user_id and password OR secret_arn at the same time." >&2
   usage
-elif [ -z "$USER_ID" -a -z "$SECRET_ARN" ]; then
-  echo "Error: You must provide either user_id and password OR secret_arn." >&2
+elif [ \( -n "$USER_ID" -o -n "$PASSWORD" \) -a \( -z "$USER_ID" -o -z "$PASSWORD" \) ]; then
+  echo "Error: Both user_id and password must be provided together." >&2
   usage
-elif [ -n "$USER_ID" -a -z "$PASSWORD" ]; then
-  echo "Error: You must provide a password when providing a user_id." >&2
+elif [ -z "$USER_ID" -a -z "$PASSWORD" -a -z "$SECRET_ARN" ]; then
+  echo "Error: You must provide either user_id and password OR secret_arn." >&2
   usage
 fi
 #
diff --git a/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_accts b/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_accts
--- a/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_accts
+++ b/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_accts
@@ -66,13 +66,11 @@ while getopts ht:je:b: opt; do
     *) usage ;;
   esac
 done
-#
-# Declare an array of required options and the error message to display if they are not set.
-declare -A required_options
-required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh tokon is required to run this script. It can be obtain from this web page:
-  https://services.cloud.netapp.com/refresh-token\n\n'
 
-check_required_options
+if [ -z "$REFRESH_TOKEN" -a -z "$BEARER_TOKEN" ]; then
+  echo "Error: You must provide either a refresh token or a bearer token." >&2
+  usage
+fi
 #
 # Check that the required commands are available.
 for cmd in jq curl; do
diff --git a/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_organization_members b/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_organization_members
--- a/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_organization_members
+++ b/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_organization_members
@@ -15,7 +15,7 @@ usage () {
   cat >&2 <<EOF
 This script is used to list all the members assigned to a BlueXP organization.
 
-Usage is: $(basename $0) -t refresh_token -o Organizaion_ID [-j] [-e ENDPOINT] [-b BEARER_TOKEN]
+Usage is: $(basename $0) -t refresh_token -o Organization_ID [-j] [-e ENDPOINT] [-b BEARER_TOKEN]
 
 Where: refresh_token - Is a refresh token used to obtain an access token needed
                        to run the Workload Factory APIs. You can obtain a refresh
@@ -38,7 +38,7 @@ EOF
 tmpout=/tmp/list_bluexp_user-out.$$
 tmpout2=/tmp/list_bluexp_user-out2.$$
 tmperr=/tmp/list_bluexp_user-err.$$
-trap 'rm -f $tmpout $tmperr' exit
+trap 'rm -f $tmpout $tmpout2 $tmperr' exit
 #
 # Source the wf_utils file.
 wf_utils=$(command -v wf_utils)
@@ -72,12 +72,15 @@ done
 #
 # Declare an array of required options and the error message to display if they are not set.
 declare -A required_options
-required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh tokon is required to run this script. It can be obtain from this web page:
-  https://services.cloud.netapp.com/refresh-token\n\n'
 required_options["ORGANIZATION_ID"]='Error: The ID of the organization is required to run this script.
 You can list a list of account by running the list_bluexp_accts script found in this repo.\n\n'
 
 check_required_options
+
+if [ -z "${REFRESH_TOKEN}" -a -z "${BEARER_TOKEN}" ]; then
+  echo "Error: Either a refresh token or a bearer token is required to run this script." >&2
+  usage
+fi
 #
 # Check that the required commands are available.
 for cmd in jq curl; do
diff --git a/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_roles b/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_roles
--- a/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_roles
+++ b/Management-Utilities/Workload-Factory-API-Samples/list_bluexp_roles
@@ -66,12 +66,11 @@ while getopts ht:je:b: opt; do
   esac
 done
 #
-# Declare an array of required options and the error message to display if they are not set.
-declare -A required_options
-required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh tokon is required to run this script. It can be obtain from this web page:
-  https://services.cloud.netapp.com/refresh-token\n\n'
-
-check_required_options
+# Check the required parameters.
+if [ -z "$REFRESH_TOKEN" -a -z "$BEARER_TOKEN" ]; then
+  echo "Error: Either a BlueXP refresh token or a Bearer token is required to run this script." >&2
+  usage
+fi
 #
 # Check that the required commands are available.
 for cmd in jq curl; do
