Allowed it to support an AWS Secret.

diff --git a/Management-Utilities/Workload-Factory-API-Samples/fsxn_credentials_set b/Management-Utilities/Workload-Factory-API-Samples/fsxn_credentials_set
--- a/Management-Utilities/Workload-Factory-API-Samples/fsxn_credentials_set
+++ b/Management-Utilities/Workload-Factory-API-Samples/fsxn_credentials_set
@@ -17,7 +17,7 @@ usage() {
 
 This script is used to set the credentials for an FSxN file system.
 
-usage: $(basename $0) -t refresh_token -a blueXP_account_ID -c credentials_ID -r aws_region -f filesystem_ID -u user_ID -p password
+usage: $(basename $0) -t refresh_token -a blueXP_account_ID -c credentials_ID -r aws_region -f filesystem_ID -u user_ID -p password -s secret_arn
 
 Where: refresh_token - Is a refresh token used to obtain an access token needed
                        to run the Workload Factory APIs. You can obtain a refresh
@@ -29,8 +29,12 @@ Where: refresh_token - Is a refresh token used to obtain an access token needed
                         credentials you have access to.
        aws_region - Is the AWS region where the file system is located.
        filesystem_ID - Is the ID of the FSxN file system.
-       user_ID - Is the user ID to set for the FSxN file system.
-       password - Is the password to set for the FSxN file system.
+       user_ID* - Is the user ID to set for the FSxN file system.
+       password* - Is the password to set for the FSxN file system.
+       secret_arn* - Is the ARN of the Secrets Manager secret that contains the
+                    credentials for the FSxN file system.
+
+*NOTE: Only user_id and password OR secret_arn can be be provided at the same time.
 
 Instead of passing parameters on the command line, you can set the
 following environment variables:
@@ -71,7 +75,7 @@ fi
 . "$wf_utils"
 #
 # Process command line options.
-while getopts "ht:a:c:r:f:u:p:" opt; do
+while getopts "ht:a:c:r:f:u:p:s:" opt; do
   case $opt in
     t) REFRESH_TOKEN="$OPTARG" ;;
     a) BLUEXP_ACCOUNT_ID="$OPTARG" ;;
@@ -80,6 +84,7 @@ while getopts "ht:a:c:r:f:u:p:" opt; do
     f) FILESYSTEM_ID="$OPTARG" ;;
     u) USER_ID="$OPTARG" ;;
     p) PASSWORD="$OPTARG" ;;
+    s) SECRET_ARN="$OPTARG" ;;
     *) usage ;;
   esac
 done
@@ -96,10 +101,16 @@ You can get a list of credentials by running the "list_credentials" script
 found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'
 required_options["AWS_REGION"]='Error: The AWS region where the file system is located is required.\n\n'
 required_options["FILESYSTEM_ID"]='Error: The ID of the FSxN file system is required.\n\n'
-required_options["USER_ID"]='Error: The user ID to set for the FSxN file system is required.\n\n'
-required_options["PASSWORD"]='Error: The password to set for the FSxN file system is required.\n\n'
 
 check_required_options
+
+if [ -n "$USER_ID" -a -n "$PASSWORD" -a -n "$SECRET_ARN" ]; then
+  echo "Error: You can only provide either user_id and password OR secret_arn at the same time." >&2
+  usage
+elif [ -z "$USER_ID" -a -z "$PASSWORD" -a -z "$SECRET_ARN" ]; then
+  echo "Error: You must provide either user_id and password OR secret_arn." >&2
+  usage
+fi
 #
 # Check that the required commands are available.
 for cmd in jq curl; do
@@ -115,4 +126,9 @@ if [ -z "$token" ]; then
   echo "Error: Failed to obtain an access token. Exiting." >&2
   exit 1
 fi
-run_curl POST "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/fsx/v2/credentials/${CREDENTIALS_ID}/regions/${AWS_REGION}/file-systems/${FILESYSTEM_ID}/ontap-credentials" "$tmpout" "$tmperr" '{"user":"'${USER_ID}'","password":"'${PASSWORD}'","resetFsxAdminPassword":false}'
+
+if [ -n "$SECRET_ARN" ]; then
+  run_curl POST "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/fsx/v2/credentials/${CREDENTIALS_ID}/regions/${AWS_REGION}/file-systems/${FILESYSTEM_ID}/ontap-credentials" "$tmpout" "$tmperr" '{"secret":"'${SECRET_ARN}'"}'
+else
+  run_curl POST "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/fsx/v2/credentials/${CREDENTIALS_ID}/regions/${AWS_REGION}/file-systems/${FILESYSTEM_ID}/ontap-credentials" "$tmpout" "$tmperr" '{"user":"'${USER_ID}'","password":"'${PASSWORD}'","resetFsxAdminPassword":false}'
+fi
