Added support for the -j option, and fixed a bug if the credentials was null.

diff --git a/Management-Utilities/Workload-Factory-API-Samples/list_credentials b/Management-Utilities/Workload-Factory-API-Samples/list_credentials
--- a/Management-Utilities/Workload-Factory-API-Samples/list_credentials
+++ b/Management-Utilities/Workload-Factory-API-Samples/list_credentials
@@ -16,7 +16,7 @@ usage() {
   cat >&2 <<EOF
 This script lists all the Workload Factory credentials you has access to.
 
-Usage: $(basename $0) -t refresh_token -a blueXP_account_ID [-o]
+Usage: $(basename $0) -t refresh_token -a blueXP_account_ID [-o] [-j]
 
 Where: refresh_token - Is a refresh token used to obtain an access token needed
                        to run the Workload Factory APIs. You can obtain a refresh
@@ -24,6 +24,7 @@ Where: refresh_token - Is a refresh token used to obtain an access token needed
        blueXP_account_ID - is the BlueXP account ID. You can find all the accounts
                            you have access to by running the "list_bluexp_accts" script
        -o means to also show the ONTAP credentials
+       -j means to output the results in JSON format instead of a table.
 
 Instead of passing parameters on the command line, you can set the
 following environment variables:
@@ -59,12 +60,14 @@ fi
 . "$wf_utils"
 #
 # Set defaults.
+raw=false
 filter="filter=$(urlencode "type eq 'AWS_ASSUME_ROLE'")"
-while getopts "ht:a:o" opt; do
+while getopts "ht:a:oj" opt; do
   case $opt in
     t) REFRESH_TOKEN="$OPTARG" ;;
     a) BLUEXP_ACCOUNT_ID="$OPTARG" ;;
     o) filter="";; # No filter, list all credentials.
+    j) raw=true ;;
     *) usage ;;
   esac
 done
@@ -93,29 +96,39 @@ if [ -z "$token" ]; then
   exit 1
 fi
 
-jq_query='.items[] | if(.type == "ONTAP") then "\(if(.metadata.fileSystemId == null) then .metadata.onPremId else .metadata.fileSystemId end) \(.type) \(.metadata.userName) \(.id) \(.numAssociatedResources)" else "\(.metadata.name) \(.type) \(.credentials | split(":") | .[4]) \(.id) \(.numAssociatedResources)" end'
+jq_query='.items[] | if(.type == "ONTAP") then "\(if(.metadata.fileSystemId != null) then .metadata.fileSystemId else if(.metadata.onPremId != null) then .metadata.onPremId else empty end end) \(.type) \(.metadata.userName) \(.id) \(.numAssociatedResources)" else "\(if(.metadata.name != null) then .metadata.name else "N/A" end) \(.type) \( if(.credentials != null) then .credentials | split(":") | .[4] else "N/A" end) \(.id) \(.numAssociatedResources)" end'
 
 run_curl GET "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/credentials/v1/credentials?$filter" $tmpout $tmperr
-if jq -r "$jq_query" $tmpout > $tmpout2 2> $tmperr; then
-  :
+if [ $raw == "true" ]; then
+  cat $tmpout
 else
-  echo "Failed to parse the output from the API."
-  cat $tmperr >&2
-  exit 1
-fi
-#
-# Check to see if there are more.
-nextToken=$(jq -r '.nextToken' $tmpout)
-while [ "$nextToken" != "null" ]; do
-  run_curl GET "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/credentials/v1/credentials?nextToken=$nextToken" $tmpout $tmperr
-  if jq -r "$jq_query" $tmpout >> $tmpout2 2> $tmperr; then
+  if jq -r "$jq_query" $tmpout > $tmpout2 2> $tmperr; then
     :
   else
     echo "Failed to parse the output from the API."
     cat $tmperr >&2
     exit 1
   fi
+fi
+#
+# Check to see if there are more.
+nextToken=$(jq -r '.nextToken' $tmpout)
+while [ "$nextToken" != "null" ]; do
+  run_curl GET "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/credentials/v1/credentials?nextToken=$nextToken" $tmpout $tmperr
+  if [ $raw == "true" ]; then
+    cat $tmpout
+  else
+    if jq -r "$jq_query" $tmpout >> $tmpout2 2> $tmperr; then
+      :
+    else
+      echo "Failed to parse the output from the API."
+      cat $tmperr >&2
+      exit 1
+    fi
+  fi
   nextToken=$(jq -r '.nextToken' $tmpout)
 done
 
-sort -f -k 2,2 -k 1,1 $tmpout2 | column -t -N "Name,Type,Account,ID,Number Associated Resources"
+if [ $raw != "true" ]; then
+  sort -f -k 2,2 -k 1,1 $tmpout2 | column -t -N "Name,Type,Account,ID,Number Associated Resources"
+fi
