Added more scripts; updated the volume_cifs_create_share to allow you to specify a path.

diff --git a/Management-Utilities/Workload-Factory-API-Samples/list_volume_cifs_shares b/Management-Utilities/Workload-Factory-API-Samples/list_volume_cifs_shares
--- a/Management-Utilities/Workload-Factory-API-Samples/list_volume_cifs_shares
+++ b/Management-Utilities/Workload-Factory-API-Samples/list_volume_cifs_shares
@@ -1,7 +1,8 @@
 #!/bin/bash
 #
 ################################################################################
-# This script is used to create the EDA Project filter user has access to.
+# This script is used to list all the cifs shares associated with a volume on
+# an ONTAP file system.
 #
 # It is dependent on the 'wf_utils' file that is included in this repo. That
 # file contains the 'get_token' function that is used to obtain a valid
@@ -14,26 +15,29 @@
 ################################################################################
 usage() {
   cat >&2 <<EOF
-This script is used to create the EDA Project filter user has access to.
+This script is used to list all the cifs shares associated with a volume on
+an ONTAP file system.
 
-Usage: $(basename $0) -t refresh_token -a blueXP_account_ID -g tag1[,tag2,...] [-y single|multiselect,single|multiselect,...]
+Usage: $(basename $0) -t refresh_token -a blueXP_account_ID -c credentials_ID -r aws_region -f filesystem_ID -v volume_ID
 
 Where: refresh_token - Is a refresh token used to obtain an access token needed
                        to run the Workload Factory APIs. You can obtain a refresh
                        token by going to https://services.cloud.netapp.com/refresh-token
        blueXP_account_ID - is the BlueXP account ID. Run 'list_bluexp_accts' to get a
-                           list of accounts you have access to.
-       -g tag1[,tag2,...] - is a comma separated list of tags to use in the filter.
-       -y single|multiselect,single|multiselect,... - is a comma separated list of filter types
-                                                      corresponding to the tags specified with the -g option.
-                                                      The filter type can be either 'single' or 'multiselect'.
-                                                      If not provided, multiselect will be used for all tags.
+                           list of accounts you have access to
+       credentials_ID    - is the Workload Factory credentials ID for the AWS account. Run
+                           'list_credentials' to get a list of credentials you have access to
+       aws_region        - is the AWS region where the FSx file systems are located
+       filesystem_id     - is the AWS file system ID of the FSx file system where the volume resides
+       volume_ID         - is the AWS volume ID of the volume where you want to create the cifs share.
 
 Instead of passing parameters on the command line, you can set the
 following environment variables:
 
     export REFRESH_TOKEN=<refresh_token>
     export BLUEXP_ACCOUNT_ID=<blueXP_account_ID>
+    export CREDENTIALS_ID=<credentials_ID>
+    export AWS_REGION=<aws_region>
 EOF
   exit 1
 }
@@ -41,10 +45,9 @@ EOF
 ################################################################################
 # Main logic starts here.
 ################################################################################
-tmpout=$(mktemp /tmp/list_volumes-out.XXXXXX)
-tmpout2=$(mktemp /tmp/list_volumes-out2.XXXXXX)
-tmperr=$(mktemp /tmp/list_volumes-err.XXXXXX)
-trap 'rm -f $tmpout $tmpout2 $tmperr' exit
+tmpout=$(mktemp /tmp/create_share-out.XXXXXX)
+tmperr=$(mktemp /tmp/create_share-err.XXXXXX)
+trap 'rm -f $tmpout $tmperr' exit
 #
 # Source the wf_utils file.
 wf_utils=$(command -v wf_utils)
@@ -62,42 +65,41 @@ EOF
 fi
 . "$wf_utils"
 #
-# Process command line arguments.
-typeset -a tags filter_types
-while getopts "ht:a:g:y:" opt; do
+# Process command line options.
+while getopts "ht:a:c:r:f:v:" opt; do
   case $opt in
     t) REFRESH_TOKEN="$OPTARG" ;;
     a) BLUEXP_ACCOUNT_ID="$OPTARG" ;;
-    g) tags=($(echo "$OPTARG" | tr ',' ' ')) ;;
-    y) filter_types=($(echo "$OPTARG" | tr ',' ' ')) ;;
+    c) CREDENTIALS_ID="$OPTARG" ;;
+    r) AWS_REGION="$OPTARG" ;;
+    f) FILESYSTEM_ID="$OPTARG" ;;
+    v) VOLUME_ID="$OPTARG" ;;
     *) usage ;;
   esac
 done
 #
 # Declare an array of required options and the error message to display if they are not set.
 declare -A required_options
-required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh tokon is required to run this script. It can be obtain from this web page:
+required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh token is required to run this script. It can be obtain from this web page:
   https://services.cloud.netapp.com/refresh-token\n\n'
 required_options["BLUEXP_ACCOUNT_ID"]='Error: A BlueXP account ID is required to run this script.
 You can get the list of accounts you have access to by running the "list_bluexp_accts" script
 found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'
+required_options["CREDENTIALS_ID"]='Error: A Worload Factory Credential ID is required to run this script.
+You can get a list of credentials by running the "list_credentials" script
+found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'
+required_options["AWS_REGION"]='Error: The AWS region where the file system is located is required.\n\n'
+required_options["FILESYSTEM_ID"]='Error: The ID of the FSxN file system is required.\n\n'
+required_options["VOLUME_ID"]='Error: An AWS Volume ID is required to run this script.
+You can get the list of file systems you have access to by running the "list_volumes" script
+found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'
 
 check_required_options
-
-if [ ${#tags[@]} -le 0 ]; then
-  echo "Error, you must specify at least one tag to use in the filter." >&2
-  usage
-else
-  if [ ${#filter_types[@]} -gt 0 -a ${#tags[@]} -ne ${#filter_types[@]} ]; then
-    echo "Error: If you specify the filter types, you must specify a filter type for all the tags." >&2
-    usage
-  fi
-fi
 #
-# Check that the required commands are available.
+# Check if the required commands are available.
 for cmd in jq curl; do
   if ! command -v $cmd &> /dev/null; then
-    echo "Error: The required command '$cmd' not found. Please install it." >&2
+    echo "Error: The required command '$cmd' was not found. Please install it." >&2
     exit 1
   fi
 done
@@ -107,36 +109,8 @@ if [ -z "$token" ]; then
   echo "Error: Failed to obtain an access token. Exiting." >&2
   exit 1
 fi
+#
+# Get the existing shares and the junction path
+run_curl GET "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/fsx/v2/credentials/${CREDENTIALS_ID}/regions/${AWS_REGION}/file-systems/${FILESYSTEM_ID}/volumes/${VOLUME_ID}?include=cifsShares" $tmpout $tmperr
+jq -r '.cifsShares[] | "\(.name),\(.path)"' $tmpout | column -t -s, -N "Share Name,Path"
 
-body='{ "filters": {"tags": ['
-i=0
-while [ $i -lt ${#tags[@]} ]; do
-  filter_type="multiselect"
-  if [ ${#filter_types[@]} -gt 0 ]; then
-    filter_type="${filter_types[$i]}"
-    if [ $filter_type != "single" -a $filter_type != "multiselect" ]; then
-      echo "Error: Invalid filter type '$filter_type' for tag '${tags[$i]}'. Filter type must be either 'single' or 'multiselect'." >&2
-      usage
-    fi
-  fi
-  body+='{
-          "key": "'${tags[$i]}'",
-          "label": "'${tags[$i]}'",
-          "type": "'$filter_type'",
-          "target": "tag"
-        }'
-  let i=i+1
-  if [ $i -lt ${#tags[@]} ]; then
-    body+=','
-  fi
-done
-body+='], "resourceProps": [ {
-          "propName": "OntapVolumeType",
-          "label": "Volume Type",
-          "type": "single" }
-      ] },
-  "status": "active" }'
-
-URL="https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/builders/v1/configure"
-run_curl POST "$token" "$URL" $tmpout $tmperr "$body"
-echo "Project filter created."
