Optimized the performance of the -a option by running each region concurrently in their own thread.

diff --git a/Management-Utilities/fsx-ontap-aws-cli-scripts/list_fsxn_svms b/Management-Utilities/fsx-ontap-aws-cli-scripts/list_fsxn_svms
--- a/Management-Utilities/fsx-ontap-aws-cli-scripts/list_fsxn_svms
+++ b/Management-Utilities/fsx-ontap-aws-cli-scripts/list_fsxn_svms
@@ -28,10 +28,11 @@
 ################################################################################
 usage () {
   cat 1>&2 <<EOF
-Usage $(basename $0) [-r region] [-a] [-n] [-p] [-i fileSystemID] [-f fileSystemName] [-e endpoint_url]
-  Where: -a means all regions
-         -n means to include file systems name
-         -p means to include the management and NAS IP address
+Usage $(basename $0) [-r region] [-a] [-X excludeRegiosn] [-n] [-p] [-i fileSystemID] [-f fileSystemName] [-e endpoint_url]
+  Where: -a means all regions.
+         -X means to exclude the specified regions (comma separated list) from the -a option.
+         -n means to include file systems name.
+         -p means to include the management and NAS IP address.
          -i means to only include SVMs that reside under the FSxN file system with the fileSystemID.
          -f means to only include SVMs that reside under the FSxN file system with the file system name.
          -e endpoint_url: Is the endpoint url to use when connecting to the AWS API.
@@ -40,12 +41,75 @@ EOF
 }
 
 ################################################################################
+# This function is used to kill a process, who's ID is passed as the first
+# argument, that is running longger than the time specified as the second
+# argurment.
+################################################################################
+start_watchdog () {
+
+  pid=$1
+  maxTime=$2
+  region=$3
+  sleep $maxTime
+  if ps -p $pid > /dev/null; then
+    printf "\nWarning, timed out while getting the list of SVMs from the $region region.\nConsider excluding it with the -X option.\n" 1>&2
+    pkill -P $pid
+    kill $pid
+  fi
+}
+
+################################################################################
+# This function will list all the SVMs in the specified region.
+################################################################################
+get_svms () {
+  region=$1
+
+  mkdir $tmpdir/$region
+  local tmpdir=$tmpdir/$region
+  tmpout=$tmpdir/output
+  tmpout2=$tmpdir/output2
+
+  if [ ! -z "$fileSystemName" ]; then
+    fileSystemID=$(aws fsx describe-file-systems $endpoint_url --output=json --region=$region 2> /dev/null | jq -r '.FileSystems[] | if((.Tags[] | select(.Key == "Name") .Value) == "'"${fileSystemName}"'") then .FileSystemId else empty end' 2> /dev/null)
+    if [ -z "$fileSystemID" ]; then
+      if [ "$allRegions" != "true" ]; then
+        echo "Error, failed to find a file system with the name '$fileSystemName'. Maybe in a different region?" 1>&2
+        return
+      else
+        #
+        # If there isn't a file system with that name in this region, then just skip region.
+        return
+      fi
+    fi
+  fi
+
+  if [ -z "$fileSystemID" ]; then
+    filter=""
+  else
+    filter="--filter Name=file-system-id,Values=$fileSystemID"
+  fi
+  aws fsx describe-storage-virtual-machines $endpoint_url --region=$region $filter | jq -r '.StorageVirtualMachines[] | "\(.FileSystemId),\(.StorageVirtualMachineId),\(.Endpoints.Nfs.IpAddresses[0]),\(.Name),\(.Lifecycle)"' 2> /dev/null | sort > $tmpout
+  if [ $includeIp == "true" ]; then
+    ipFmt="%16s"
+    ipHeader="IP"
+  else
+    ipFmt="%0s"
+    ipHeader=""
+  fi
+  
+  if [ $includeFsName == "true" ]; then
+    aws fsx describe-file-systems $endpoint_url --region=$region | jq -r '.FileSystems[] | .FileSystemId + "," + (.Tags[] | select(.Key == "Name") .Value)' > $tmpout2
+    awk -F, -v region=$region -v ipFmt=$ipFmt -v ipHeader=$ipHeader 'BEGIN {first=1; maxNameLen=0; while(getline < "'$tmpout2'") {fss[$1]=$2; if(length($2) > maxNameLen) {maxNameLen=length($2)}}; maxNameLen +=2; formatStr="%12s %20s%-"maxNameLen"s %23s "ipFmt" %13s %s\n"}; {if(first) {printf "\n"; printf formatStr, "Region", "FileSystem ID", "(Name)", "SVM ID", ipHeader, "State", "SVM Name"; first=0}; if(ipHeader != "IP") {ip=""} else {ip=$3}; name="("fss[$1]")"; printf formatStr, region, $1, name, $2, ip, $5, $4}' < $tmpout
+  else
+    awk -F, -v region=$region -v ipFmt=$ipFmt -v ipHeader=$ipHeader 'BEGIN {first=1; formatStr="%12s %23s %23s "ipFmt" %13s %s\n"}; {if(first) {printf "\n"; printf formatStr, "Region", "FileSystem ID", "SVM ID", ipHeader, "State", "SVM Name"; first=0}; if(ipHeader != "IP") {ip=""} else {ip=$3}; printf formatStr, region, $1, $2, ip, $5, $4}' < $tmpout
+  fi
+}
+
+################################################################################
 # Main logic starts here.
 ################################################################################
-
-tmpout=/tmp/list_aws_svms-out.$$
-tmpout2=/tmp/list_aws_svms-out2.$$
-trap 'rm -f $tmpout $tmpout2' exit
+export tmpdir=$(mktemp -d /tmp/list_fsxn_svm.XXXXXX)
+trap 'rm -fr $tmpdir' EXIT
 #
 # Check that the required utilities are installed.
 if which aws jq > /dev/null 2>&1; then
@@ -60,11 +124,14 @@ allRegions=false
 includeFsName=false
 includeIp=false
 region=$(aws configure get region)
-while getopts "hanr:i:f:pe:" option; do
+excludeRegions="none"
+while getopts "haX:nr:i:f:pe:" option; do
   case "$option" in
     r) region="$OPTARG"
       ;;
     a) allRegions=true
+      ;;
+    X) excludeRegions="$(echo $OPTARG | sed -e 's/,/|/g' | sed -e 's/ //g')"
       ;;
     n) includeFsName=true
       ;;
@@ -92,7 +159,7 @@ if [ "$allRegions" = "true" ]; then
   # intersection of all the regions they have enabled, and the regions that
   # support FSxN
   allEndabledRegions=$(aws ec2 describe-regions --query "Regions[].RegionName" --output=json | jq -r '.[]')
-  allFsxnRegions=$(curl -s https://api.regional-table.region-services.aws.a2z.com/index.json | jq -r '.prices[] | select(.attributes."aws:serviceName" == "Amazon FSx for NetApp ONTAP") .attributes."aws:region"')
+  allFsxnRegions=$(curl -s https://api.regional-table.region-services.aws.a2z.com/index.json | jq -r '.prices[] | select(.attributes."aws:serviceName" == "Amazon FSx for NetApp ONTAP") .attributes."aws:region"' | egrep -v "$excludeRegions")
   for reg in $allEndabledRegions; do
     for fsxnReg in $allFsxnRegions; do
       if [ $reg == $fsxnReg ]; then
@@ -109,39 +176,20 @@ else
 fi
 #
 # Loop on all the regions.
+declare -A pids
 for region in ${regions[*]}; do
-  if [ ! -z "$fileSystemName" ]; then
-    fileSystemID=$(aws fsx describe-file-systems $endpoint_url --output=json --region=$region 2> /dev/null | jq -r '.FileSystems[] | if((.Tags[] | select(.Key == "Name") .Value) == "'"${fileSystemName}"'") then .FileSystemId else empty end' 2> /dev/null)
-    if [ -z "$fileSystemID" ]; then
-      if [ "$allRegions" != "true" ]; then
-        echo "Error, failed to find a file system with the name '$fileSystemName'. Maybe in a different region?" 1>&2
-        exit 1
-      else
-        #
-        # If there isn't a file system with that name in this region, then just skip region.
-        continue
-      fi
-    fi
-  fi
+  get_svms $region > $tmpdir/$region.out &
+  pids[$!]=$region
+  start_watchdog $! 20 $region &
+done
 
-  if [ -z "$fileSystemID" ]; then
-    filter=""
+while [ ${#pids[@]} -gt 0 ]; do
+  wait -n -p pid ${!pids[@]}
+  if [ $? -ne 127 ]; then
+    cat $tmpdir/${pids[$pid]}.out
+    unset pids[$pid]
   else
-    filter="--filter Name=file-system-id,Values=$fileSystemID"
-  fi
-  aws fsx describe-storage-virtual-machines $endpoint_url --region=$region $filter | jq -r '.StorageVirtualMachines[] | "\(.FileSystemId),\(.StorageVirtualMachineId),\(.Endpoints.Nfs.IpAddresses[0]),\(.Name),\(.Lifecycle)"' | sort > $tmpout
-  if [ $includeIp == "true" ]; then
-    ipFmt="%16s"
-    ipHeader="IP"
-  else
-    ipFmt="%0s"
-    ipHeader=""
-  fi
-  
-  if [ $includeFsName == "true" ]; then
-    aws fsx describe-file-systems $endpoint_url --region=$region | jq -r '.FileSystems[] | .FileSystemId + "," + (.Tags[] | select(.Key == "Name") .Value)' > $tmpout2
-    awk -F, -v region=$region -v ipFmt=$ipFmt -v ipHeader=$ipHeader 'BEGIN {first=1; maxNameLen=0; while(getline < "'$tmpout2'") {fss[$1]=$2; if(length($2) > maxNameLen) {maxNameLen=length($2)}}; maxNameLen +=2; formatStr="%12s %20s%-"maxNameLen"s %23s "ipFmt" %13s %s\n"}; {if(first) {printf "\n"; printf formatStr, "Region", "FileSystem ID", "(Name)", "SVM ID", ipHeader, "State", "SVM Name"; first=0}; if(ipHeader != "IP") {ip=""} else {ip=$3}; name="("fss[$1]")"; printf formatStr, region, $1, name, $2, ip, $5, $4}' < $tmpout
-  else
-    awk -F, -v region=$region -v ipFmt=$ipFmt -v ipHeader=$ipHeader 'BEGIN {first=1; formatStr="%12s %23s %23s "ipFmt" %13s %s\n"}; {if(first) {printf "\n"; printf formatStr, "Region", "FileSystem ID", "SVM ID", ipHeader, "State", "SVM Name"; first=0}; if(ipHeader != "IP") {ip=""} else {ip=$3}; printf formatStr, region, $1, $2, ip, $5, $4}' < $tmpout
+    echo "Error, waiting for an non-existent process. This should never happen." 1>&2
+    exit 1
   fi
 done
