Fixed a typo

diff --git a/Management-Utilities/fsx-ontap-aws-cli-scripts/list_fsxn_volumes b/Management-Utilities/fsx-ontap-aws-cli-scripts/list_fsxn_volumes
--- a/Management-Utilities/fsx-ontap-aws-cli-scripts/list_fsxn_volumes
+++ b/Management-Utilities/fsx-ontap-aws-cli-scripts/list_fsxn_volumes
@@ -182,7 +182,7 @@ for region in ${regions[*]}; do
     else
       if [ $extraInfo == "true" ]; then
         if [ $(wc -l $volumeList | awk '{print $1}') -gt 500 ]; then
-          echo "Sorry, too many volumes to get CloudWatch statics for."
+          echo "Sorry, too many volumes to get CloudWatch statistics for."
         else
           volIds=$(awk -F, '{print $3}' < $volumeList)
           if [ ! -z "$volIds" ]; then
@@ -220,6 +220,11 @@ EOF
             done
             echo "]" >> $cloudwatchQueryFile
             aws cloudwatch get-metric-data --region $region --metric-data-queries file://$cloudwatchQueryFile --start-time=$(date -u -d '5 minutes ago' +"%Y-%m-%dT%H:%M:%SZ") --end-time=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --output=json > $cloudwatchOutputFile
+            if [ $? -ne 0 ]; then
+              cat $cloudwatchOutputFile 1>&2
+              echo "Error, failed to get CloudWatch metrics." 1>&2
+              exit 1
+            fi
             for volId in $volIds; do
               volId2=$(echo $volId | sed -e 's/-/_/g')
               capacity=$(jq -r '.MetricDataResults[] | select(.Id == "m'$volId2'") | .Values[0] // 0' < $cloudwatchOutputFile)
