Added a set fsxn password script.

diff --git a/Management-Utilities/fsx-ontap-aws-cli-scripts/set_fsxn_password b/Management-Utilities/fsx-ontap-aws-cli-scripts/set_fsxn_password
--- a/Management-Utilities/fsx-ontap-aws-cli-scripts/set_fsxn_password
+++ b/Management-Utilities/fsx-ontap-aws-cli-scripts/set_fsxn_password
@@ -9,14 +9,16 @@
 ################################################################################
 usage () {
 cat 1>&2 <<EOF
-Usage: $(basename $0) -p password [-f fileSystemName] [-i fileSystemId] [-r region] [-w] [-e endpoint_url]
+Usage: $(basename $0) [-p password] [-f fileSystemName] [-i fileSystemId] [-r region] [-w] [-e endpoint_url]
 Where:
-  password: Is the password to set for the fsxadmin user.
-  fileSystemName: Is the name of the FSxN file system where you want the SVM created. This option is mutually exclusive with the -i option.
-  fileSystemID: Is the file system ID where you want to create the SVM on. This option is mutually exclusive with the -f option.
+  password: Is the password to set for the fsxadmin user. If not provided, the script will prompt for it.
+  fileSystemName: Is the name of the FSxN file system where you want set the password. This option is mutually exclusive with the -i option.
+  fileSystemID: Is the file system ID where you want to set the password. This option is mutually exclusive with the -f option.
   region: Is the AWS region where the FSxN file system resides.
-  -w : Wait for the SVM to be created before returning.
+  -w : Wait for the password to be set before returning.
   endpoint_url: Is the endpoint url to use when connecting to the AWS API.
+
+NOTE: You must provide either the file system name or the file system ID. You cannot provide both.
 EOF
   exit 1
 }
@@ -64,6 +66,12 @@ if [ ! -z "$fileSystemName" -a ! -z "$fsid" ]; then
   echo "Error, you can only specify the -i OR the -f option. Not both." 1>&2
   usage
 fi
+#
+# Ensure all the required parameters have been provided.
+if [ -z "$fileSystemName" -a -z "$fsid" ]; then
+  echo "Error, missing required arguments." 1>&2
+  usage
+fi
 
 if [ -z "$password" ]; then
   read -sp "Enter the password to set for the fsxadmin user: " password1
@@ -79,8 +87,8 @@ if [ -z "$password" ]; then
 fi
 #
 # Ensure all the required parameters have been provided.
-if [ -z "$password" -o -z "$fileSystemName" -a -z "$fsid" ]; then
-  echo "Error, missing required arguments." 1>&2
+if [ -z "$password" ]; then
+  echo "Error, the password can't be blank."
   usage
 fi
 #
@@ -95,7 +103,7 @@ if [ -z "$fsid" ]; then
 fi
 #
 # Set the password
-aws fsx update-file-system $endpoint_url --ontap-configuration '{"FsxAdminPassword": "'$password'"}'  --region=$region --file-system-id "$fsid" --output=json > $tmpout 2>&1
+aws fsx update-file-system $endpoint_url --ontap-configuration '{"FsxAdminPassword": "'"$password"'"}'  --region=$region --file-system-id "$fsid" --output=json > $tmpout 2>&1
 if [ $? != "0" ]; then
   echo "Failed to set the password." 1>&2
   cat $tmpout 1>&2
